# Generated by Django 2.2.10 on 2020-09-09 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board_Thickness_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_thickness', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
        migrations.CreateModel(
            name='Canvas_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_choices', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Location_eng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Location_geo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Location_rus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Paints_Acrylic_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=15)),
                ('color_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Paints_Gouache_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=15)),
                ('color_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Paints_Oil_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=15)),
                ('color_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Paints_Other_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=15)),
                ('color_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Paints_Water_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=15)),
                ('color_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pastels_Dry_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=15)),
                ('color_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pastels_Oil_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=15)),
                ('color_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pastels_Soft_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=15)),
                ('color_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pastels_Water_Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=15)),
                ('color_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pencils_Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', models.CharField(max_length=15)),
                ('color_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_geo', models.CharField(default='', max_length=50)),
                ('product_name_eng', models.CharField(default='', max_length=50)),
                ('product_name_rus', models.CharField(default='', max_length=50)),
                ('description_geo', models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(40)])),
                ('description_eng', models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(40)])),
                ('description_rus', models.CharField(default='', max_length=300, validators=[django.core.validators.MinLengthValidator(40)])),
                ('image_low_quality', models.ImageField(default='', upload_to='static/media/shop/images')),
                ('image_high_quality', models.ImageField(default='', upload_to='static/media/shop/images')),
                ('price', models.FloatField()),
                ('amount_in_warehouse', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Brand')),
                ('location_eng', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Location_eng')),
                ('location_geo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Location_geo')),
                ('location_rus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Location_rus')),
            ],
        ),
        migrations.CreateModel(
            name='Water_Color_Sheet_Size_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_size', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Accessories_Auxiliary_Fluids',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(default='', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Accessories_Mastehin',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(default='', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Accessories_Molbert',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(default='', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Accessories_Palette',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(default='', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Canvas_circular_frame',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('material', models.CharField(default='', max_length=30)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Canvas_rectangle_frame',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('material', models.CharField(default='', max_length=30)),
                ('thickness', models.CharField(blank=True, choices=[('20mmX30mm', '20mmX30mm'), ('20mmX40mm', '20mmX40mm'), ('25mmX50mm', '25mmX50mm')], max_length=30, null=True)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Water_color_sheet',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('color', models.CharField(default='', max_length=40)),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Water_Color_Sheet_Size_Choices')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Tree_drawing_board',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('thickness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Board_Thickness_Choices')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Pencil',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(choices=[('GRAFFITI', 'GRAFFITI'), ('WATER COLOR', 'WATER COLOR'), ('COAL', 'COAL'), ('OTHER', 'OTHER')], max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Pencils_Colors')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Pastel_Water_Color_Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(choices=[('OIL', 'OIL'), ('SOFT', 'SOFT'), ('WATER COLOR', 'WATER COLOR'), ('DRY', 'DRY')], default='WATER COLOR', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Pastels_Water_Color')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Pastel_Soft_Color_Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(choices=[('OIL', 'OIL'), ('SOFT', 'SOFT'), ('WATER COLOR', 'WATER COLOR'), ('DRY', 'DRY')], default='SOFT', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Pastels_Soft_Color')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Pastel_Oil_Color_Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(choices=[('OIL', 'OIL'), ('SOFT', 'SOFT'), ('WATER COLOR', 'WATER COLOR'), ('DRY', 'DRY')], default='OIL', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Pastels_Oil_Color')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Pastel_Dry_Color_Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(choices=[('OIL', 'OIL'), ('SOFT', 'SOFT'), ('WATER COLOR', 'WATER COLOR'), ('DRY', 'DRY')], default='DRY', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Pastels_Dry_Color')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Paint_Water_Color_Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(choices=[('OIL COLOR', 'OIL COLOR'), ('ACRYLIC COLOR', 'ACRYLIC COLOR'), ('GOUACHE', 'GOUACHE'), ('WATER COLOR', 'WATER COLOR'), ('OTHER', 'OTHER')], default='WATER COLOR', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Paints_Water_Color')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Paint_Other_Color_Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(choices=[('OIL COLOR', 'OIL COLOR'), ('ACRYLIC COLOR', 'ACRYLIC COLOR'), ('GOUACHE', 'GOUACHE'), ('WATER COLOR', 'WATER COLOR'), ('OTHER', 'OTHER')], default='OTHER', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Paints_Other_Color')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Paint_Oil_Color_Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(choices=[('OIL COLOR', 'OIL COLOR'), ('ACRYLIC COLOR', 'ACRYLIC COLOR'), ('GOUACHE', 'GOUACHE'), ('WATER COLOR', 'WATER COLOR'), ('OTHER', 'OTHER')], default='OIL COLOR', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Paints_Oil_Color')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Paint_Gouache_Color_Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(choices=[('OIL COLOR', 'OIL COLOR'), ('ACRYLIC COLOR', 'ACRYLIC COLOR'), ('GOUACHE', 'GOUACHE'), ('WATER COLOR', 'WATER COLOR'), ('OTHER', 'OTHER')], default='GOUACHE', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Paints_Gouache_Color')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Paint_Acrylic_Color_Product',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(default='', max_length=40)),
                ('material', models.CharField(choices=[('OIL COLOR', 'OIL COLOR'), ('ACRYLIC COLOR', 'ACRYLIC COLOR'), ('GOUACHE', 'GOUACHE'), ('WATER COLOR', 'WATER COLOR'), ('OTHER', 'OTHER')], default='ACRYLIC COLOR', max_length=30)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Paints_Acrylic_Color')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Drawing_canvas',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('height', models.CharField(default='', max_length=40)),
                ('drawing_canvas_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Canvas_Choices')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Canvas_with_rectangle_frame',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('material', models.CharField(default='', max_length=30)),
                ('thickness', models.CharField(blank=True, choices=[('20mmX30mm', '20mmX30mm'), ('20mmX40mm', '20mmX40mm'), ('25mmX50mm', '25mmX50mm')], max_length=30, null=True)),
                ('overlay_geo', models.CharField(blank=True, choices=[('გვერდზე', 'გვერდზე'), ('უკან', 'უკან')], max_length=30, null=True)),
                ('overlay_eng', models.CharField(blank=True, choices=[('around', 'around'), ('back', 'back')], max_length=30, null=True)),
                ('overlay_rus', models.CharField(blank=True, choices=[('на странице', 'на странице'), ('назад', 'назад')], max_length=30, null=True)),
                ('pack', models.CharField(choices=[('ერთი', 'ერთი'), ('კოლექცია', 'კოლექცია')], default='ერთი', max_length=20)),
                ('canvas_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Canvas_Choices')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Canvas_with_circular_frame',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('amount_volume', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('material', models.CharField(default='', max_length=30)),
                ('overlay_geo', models.CharField(blank=True, choices=[('გვერდზე', 'გვერდზე'), ('უკან', 'უკან')], max_length=30, null=True)),
                ('overlay_eng', models.CharField(blank=True, choices=[('around', 'around'), ('back', 'back')], max_length=30, null=True)),
                ('overlay_rus', models.CharField(blank=True, choices=[('на странице', 'на странице'), ('назад', 'назад')], max_length=30, null=True)),
                ('canvas_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Canvas_Choices')),
            ],
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='Canvas_with_carton',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('size', models.CharField(default='', max_length=40)),
                ('drawing_canvas_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Canvas_Choices')),
            ],
            bases=('shop.product',),
        ),
    ]
