# Generated by Django 2.2.10 on 2020-09-09 15:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulTransaction',
            fields=[
                ('transaction_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('delivery', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('total_price', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.SuccessfulTransaction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
