# Generated by Django 3.0.7 on 2020-09-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfultransaction',
            name='order_code',
            field=models.CharField(default=0, editable=False, max_length=5),
        ),
    ]
